swagger.yaml
Includes endpoints and data models.
=> Swagger spec file for the resource api

.gitignore, dp-code-list-api.nomad
=> Add nomad file.

vendor/github.com/gopherjs/gopherjs/LICENSE, vendor/github.com/gopherjs/gopherjs/js/js.go, vendor/github.com/gorilla/context/LICENSE, vendor/github.com/gorilla/context/README.md, vendor/github.com/gorilla/context/context.go, vendor/github.com/gorilla/context/doc.go, vendor/vendor.json
Update the vendored dependencies 
Sanity check / check areas using dependencies continue to function
Anyone
=> Add missing dependencies

scripts/README.md, scripts/setup.sh
=> add `setup.sh --env` arg to adjust port when setting up remote env

scripts/README.md
arbitrary fix to force a build
approve it
anyone
=> Uppercase JSON in readme

cmd/dp-code-list-api/main.go, config/config.go, config/config_test.go, store/mongo.go
Make mongo details configurable
check functionality and run acceptance tests
anyone
=> Add config vars for mongo database and collections

cmd/dp-code-list-api/main.go, config/config.go, config/config_test.go, store/mongo.go
=> Updating cmd-master from cmd-develop

README.md
update README with correct port, missing vars
=> correct README config - port was wrong, add mongodb vars

scripts/README.md, scripts/add.go, scripts/setup.sh
Ansible should be the only method on creating and dropping
indexes. As creating any additional changes will make them
untracked and report changed states for the indexes.
review the bash script
anyone
=> Only create indexes from ansible

swagger.yaml
Update summaries and descriptions to standardize for dev site
Check swagger spec is still valid
Check updates make things clearer
Anyone
=> Update title and description in spec to be more useful

swagger.yaml
Remove offset and limit from specs because they're not used parameters right now
Check spec is true and offset and limit have been removed as parameters
Anyone
=> Remove offset and limit from spec

api/api.go
Added assignment for limit and count to list endpoints. Until pagination is in place, these will be the same.
Make sure count and limit are accurate and all other data is still being returned.
Anyone
=> Update list responses to accurately reflect count and limit

api/api.go
Also assign count to total count
Check all relevant values are populated on return
Anyone
=> Add assignment to TotalCount for lists

vendor/github.com/ONSdigital/go-ns/LICENSE.md, vendor/github.com/ONSdigital/go-ns/common/client.go, vendor/github.com/ONSdigital/go-ns/common/errors.go, vendor/github.com/ONSdigital/go-ns/common/identity.go, vendor/github.com/ONSdigital/go-ns/common/models.go, vendor/github.com/ONSdigital/go-ns/common/rchttp.go, vendor/github.com/ONSdigital/go-ns/log/log.go, vendor/vendor.json
* Update log package to ensure log messages are correct
=> Update log package to ensure log messages are correct

models/dataset.go, store/datasets_test.go, store/neo4j.go
Reworked the response model of /datasets to aggregate editions and show the latest version link
Review changes / test
Anyone
=> Refactor /datasets response model to group editions

cmd/dp-code-list-api/main.go, config/config.go, config/config_test.go, models/links.go, models/links_test.go, store/mapper/code_lists.go, store/mapper/codes.go, store/mapper/codes_test.go, store/mapper/common.go, store/mapper/datasets.go, store/mapper/editions.go, store/mapper/mapper.go, store/neo4j.go, store/neo4j_datasets_test.go, store/neo4j_editions_exist_test.go, store/neo4j_get_codeList_test.go, store/neo4j_get_codeLists_test.go, store/neo4j_get_code_test.go, store/neo4j_get_codes_test.go, store/neo4j_get_edition_test.go, store/neo4j_get_editions_test.go
The graph stores relative paths not fully qualified URLs (rightly so) and when not making requests through the API router links don't work as they have no host.
- Added config for code list api host name
- Add configured host name to all URLs returned by the API
Check full local URLs are provided by default
Check updating the config overwrites correctly
Check paths still get updated correctly through the API router
anyone
=> Add api domain config and prepend to links

store/neo4j_datasets_test.go
The test would intermittently fail if the results came back in the wrong order.
Refactored so each check is a function, and results are looped over to process the right result with the right function, or error if something unexpected happens.
Check tests pass consistently
anyone
=> Refactor dataset list test to handle unknown list order

cmd/dp-code-list-api/main.go, config/config.go, store/mapper/mapper.go, store/neo4j.go
Add Dataset API host url for datasets endpoint
- check datasets endpoint returns more useful links
anyone
=> Add Dataset API host url for datasets endpoint

dp-code-list-api.nomad
What
Using docker reduces the likelihood of timeout on deploy
How to review
check for typos
check repo names are consistent
check web/publishing both updated
Who can review
anyone
=> Update nomad plan to use docker instead of exec driver

Makefile, README.md
Remove unused config items where they have been moved to the dp-graph abstraction
sanity check 
anyone
=> Remove unused config items from README

api/code-lists.go, api/codes.go, api/datasets.go, api/editions.go
Add logging to editions handlers and make consistent
check log messages make sense
anyone
=> Add logging to editions handlers and make consistent

vendor/github.com/ONSdigital/dp-graph/neo4j/codelists.go, vendor/github.com/ONSdigital/dp-graph/neo4j/query/query.go, vendor/vendor.json
This means /code-lists/invalidID should actually return a 404, not a 200
check 200s/404s happen in correct places
anyone
=> Update dp-graph vendor so /code-lists/<id> returns not found correctly

models/dataset.go, models/links.go
This link should be specific to the dataset, as each document in the list is a dataset
check all lnks from the `/codes/<code>/datasets` endpoint seem correct
anyone
=> Update dataset UpdateLinks function so self is the dataset API doc

README.md
Force signed commit
check verification
anyone
=> Force signed commit

README.md
Make readme more correct
make sure the last commit is signed (not currently building)
check commit is signed
anyone
=> Update README to include all config items

Makefile, ci/audit.yml, ci/scripts/audit.sh
Updated Makefile to include dependency auditing process and created audit scripts for CI
Check that the changes make sense, that permissions are set correctly (`chmod 755`), and that the `audit` command works as expected
Anyone
=> add vulnerability auditing

go.mod, go.sum
- Upgrade dp-graph to include datasets for a code query fix
Sanity check
Anyone
=> Release 2.5.1

api/api.go, api/codelists.go, api/codelists_test.go, api/codes.go, api/codes_test.go, api/datasets.go, api/datasets_test.go, api/editions_test.go
- removed http.Error on w.Write error handling, which would trigger another error
- fixed/removed tests accordingly
- Make sure code changes make sense
- Make sure unit tests pass
anyone
=> removed http.Error on w.Write error handling, which would trigger another error

dp-code-list-api.nomad
As per title.
Ensure changes are similar to whats in babbage for 'spread'.
Anyone.
=> Ensure deployments spread over availability zones

Dockerfile.local
Describe what you have changed and why.
Describe the steps required to test the changes.
Describe who worked on the changes, so that other people can review.
=> keep dp-compose docker go version uptodate with go.mod
